spring.application.name=PediatricsDiabeticSoftware
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.port = 8080

spring.datasource.url=jdbc:postgresql://localhost:5432/pediatrics
spring.datasource.username=postgres
spring.datasource.password=transport
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mvc.view.prefix: /WEB-INF/views/
spring.mvc.view.suffix: .jsp